version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    networks:
    - monitoring-network
    volumes:
    - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana
    networks:
    - monitoring-network
    ports:
    - "3000:3000"
    volumes:
    - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
    - prometheus

  node-exporter:
    image: "prom/node-exporter"
    networks:
    - monitoring-network
    ports:
    - "9100:9100"
    depends_on:
    - prometheus

  mysql:
    image: "mysql"
    networks:
    - monitoring-network
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=monitoring

  mysql-exporter:
    image: "prom/mysqld-exporter"
    networks:
    - monitoring-network
    ports:
    - "9104:9104"
    environment:
    - DATA_SOURCE_NAME=root:secret@(mysql:3306)/
    depends_on:
    - mysql

  micrometer-app:
    image: "docker.io/library/micrometer:0.0.1-SNAPSHOT"
    networks:
    - monitoring-network
    ports:
    - "8080:8080"
    depends_on:
    - "mysql"
    environment:
    - spring.datasource.url=jdbc:mysql://mysql:3306/monitoring?useSSL=false

networks:
  monitoring-network:
    driver: bridge
