{
 "title": "Java Micrometer",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(cpu, kubernetes_namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(cpu{kubernetes_namespace =\"$namespace\"}, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Uptime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{kubernetes_pod_name=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "singlestat",
   "description": "The starttime of the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_starttime_seconds{kubernetes_pod_name=\"$pod_name\"} * 1000"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processor Count",
   "type": "singlestat",
   "description": "The number of processors available to the Java virtual machine",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cpu{kubernetes_pod_name=~\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Average CPU Load",
   "type": "graph",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_load_average{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warn Events",
     "type": "singlestat",
     "description": "Number of warn level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{kubernetes_pod_name=~\"$pod_name\", level=\"warn\"}"
      }
     ]
    },
    {
     "title": "Debug Events",
     "type": "singlestat",
     "description": "Number of debug level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{kubernetes_pod_name=~\"$pod_name\", level=\"debug\"}"
      }
     ]
    },
    {
     "title": "Error Events",
     "type": "singlestat",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{kubernetes_pod_name=~\"$pod_name\", level=\"error\"}"
      }
     ]
    },
    {
     "title": "Trace Events",
     "type": "singlestat",
     "description": "Number of trace level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{kubernetes_pod_name=~\"$pod_name\", level=\"trace\"}"
      }
     ]
    },
    {
     "title": "Info Events",
     "type": "singlestat",
     "description": "Number of info level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{kubernetes_pod_name=~\"$pod_name\", level=\"info\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Thread Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads Peak",
     "type": "graph",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_peak{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live Daemon Threads",
     "type": "graph",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live Total Threads",
     "type": "graph",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Count",
     "type": "graph",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer Mem Used",
     "type": "graph",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer Capacity",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Data Size",
     "type": "graph",
     "description": "Max size of old generation memory pool",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_max_data_size_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "graph",
     "description": "Size of old generation memory pool after a full GC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Promotion Rate",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_promotion_rate_total{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "graph",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_allocation_rate_total{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Pause Count",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_duration_seconds_count{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{cause}} ({{action}})"
      }
     ]
    },
    {
     "title": "Pause Duration",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_duration_seconds_sum{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{cause}} ({{action}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Class Loader Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_unloaded_total{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Count",
     "type": "graph",
     "description": "Count of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_duration_seconds_count{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Requests Time",
     "type": "graph",
     "description": "Timer of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_duration_seconds_sum{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    }
   ]
  }
 ]
}